projects:
  graphql:
    schemaPath: src/graphql/schema.json
    includes:
      - amplify/backend/api/graphql
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/graphql
extensions:
  amplify:
    version: 3
